# Generated by Django 4.2.3 on 2023-07-28 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_5', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registroUsuarios',
            new_name='registroClientes',
        ),
    ]
